stages:
  - test

variables:
  PYTHON_VERSION: "3.11"

default:
  image: python:$PYTHON_VERSION
  before_script:
    - pip install --upgrade pip
    - pip install .[testing]

test:
  stage: test
  script:
    - pytest  # All options are read from setup.cfg
  artifacts:
    when: always
    reports:
      junit: report.xml  # Matches --junitxml in setup.cfg
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml  # Matches --cov-report=xml in setup.cfg
    paths:
      - coverage.xml
      - report.xml