name: sysvar
channels:
  - conda-forge
dependencies:
  - python
  - pip
  - numpy
  - scipy
  - pandas
  - tqdm
  - matplotlib
  - seaborn
  - pytest
  - pytest-cov
  - tox
  - pre_commit
  - nbdime
  - nbstripout
  - sphinx
  - recommonmark
  - uncertainties
  - uproot
  - pyyaml
  - particle
  - pandoc
