correction_type: 1D

dependant_variable: p # This has to be the name of the basf2 variable
unit: GeV
title: $\mathrm{\pi^{+}_{s}}$

min: [0.5, 1.0]
max: [1.0, 2.0]
corrections: [1.5, 0.5]

uncertainties:
  fully_correlated:
    stat_corr: [0.02, 0.02]
    sys: [0.0032, 0.003, 0.001]
  uncorrelated:
    stat_uncorr: [0.03, 0.04,]

# The prefix will be added here
extra_cuts:
  PDG: [211, -211]

cov_matrix: